// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/fastls.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康检查请求
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_fastls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fastls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_fastls_proto_rawDescGZIP(), []int{0}
}

// 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_fastls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fastls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_fastls_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// HTTP请求
type FetchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                                                                   // 请求URL（必填）
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                                                                             // HTTP方法，默认GET
	Headers         map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 请求头
	Body            string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // 请求体
	Proxy           string                 `protobuf:"bytes,5,opt,name=proxy,proto3" json:"proxy,omitempty"`                                                                               // 代理地址
	Timeout         int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                          // 超时时间（秒），默认30
	DisableRedirect bool                   `protobuf:"varint,7,opt,name=disable_redirect,json=disableRedirect,proto3" json:"disable_redirect,omitempty"`                                   // 是否禁用重定向
	UserAgent       string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`                                                      // User-Agent
	Fingerprint     *Fingerprint           `protobuf:"bytes,9,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                                                                   // 指纹配置
	Browser         string                 `protobuf:"bytes,10,opt,name=browser,proto3" json:"browser,omitempty"`                                                                          // 浏览器类型
	Cookies         []*Cookie              `protobuf:"bytes,11,rep,name=cookies,proto3" json:"cookies,omitempty"`                                                                          // Cookie列表
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_fastls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fastls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_fastls_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FetchRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FetchRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *FetchRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *FetchRequest) GetDisableRedirect() bool {
	if x != nil {
		return x.DisableRedirect
	}
	return false
}

func (x *FetchRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *FetchRequest) GetFingerprint() *Fingerprint {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *FetchRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *FetchRequest) GetCookies() []*Cookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

// 指纹配置
type Fingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`   // 指纹类型: "ja3" 或 "ja4r"
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 指纹值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fingerprint) Reset() {
	*x = Fingerprint{}
	mi := &file_proto_fastls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fingerprint) ProtoMessage() {}

func (x *Fingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fastls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fingerprint.ProtoReflect.Descriptor instead.
func (*Fingerprint) Descriptor() ([]byte, []int) {
	return file_proto_fastls_proto_rawDescGZIP(), []int{3}
}

func (x *Fingerprint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Fingerprint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Cookie
type Cookie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Expires       int64                  `protobuf:"varint,5,opt,name=expires,proto3" json:"expires,omitempty"` // Unix时间戳
	HttpOnly      bool                   `protobuf:"varint,6,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	Secure        bool                   `protobuf:"varint,7,opt,name=secure,proto3" json:"secure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	mi := &file_proto_fastls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fastls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_proto_fastls_proto_rawDescGZIP(), []int{4}
}

func (x *Cookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Cookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cookie) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Cookie) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *Cookie) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

// HTTP响应
type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                                                                    // 是否成功
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                                                                            // HTTP状态码
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应头
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // 响应体
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                                               // 错误信息（如果有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_fastls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fastls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_fastls_proto_rawDescGZIP(), []int{5}
}

func (x *FetchResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FetchResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FetchResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_fastls_proto protoreflect.FileDescriptor

const file_proto_fastls_proto_rawDesc = "" +
	"\n" +
	"\x12proto/fastls.proto\x12\x06fastls\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xba\x03\n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12;\n" +
	"\aheaders\x18\x03 \x03(\v2!.fastls.FetchRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x14\n" +
	"\x05proxy\x18\x05 \x01(\tR\x05proxy\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x12)\n" +
	"\x10disable_redirect\x18\a \x01(\bR\x0fdisableRedirect\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\x125\n" +
	"\vfingerprint\x18\t \x01(\v2\x13.fastls.FingerprintR\vfingerprint\x12\x18\n" +
	"\abrowser\x18\n" +
	" \x01(\tR\abrowser\x12(\n" +
	"\acookies\x18\v \x03(\v2\x0e.fastls.CookieR\acookies\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\vFingerprint\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xad\x01\n" +
	"\x06Cookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x18\n" +
	"\aexpires\x18\x05 \x01(\x03R\aexpires\x12\x1b\n" +
	"\thttp_only\x18\x06 \x01(\bR\bhttpOnly\x12\x16\n" +
	"\x06secure\x18\a \x01(\bR\x06secure\"\xdb\x01\n" +
	"\rFetchResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".fastls.FetchResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012~\n" +
	"\rFastlsService\x127\n" +
	"\x06Health\x12\x15.fastls.HealthRequest\x1a\x16.fastls.HealthResponse\x124\n" +
	"\x05Fetch\x12\x14.fastls.FetchRequest\x1a\x15.fastls.FetchResponseB3Z1github.com/ChengHoward/Fastls/main/rpc/grpc/protob\x06proto3"

var (
	file_proto_fastls_proto_rawDescOnce sync.Once
	file_proto_fastls_proto_rawDescData []byte
)

func file_proto_fastls_proto_rawDescGZIP() []byte {
	file_proto_fastls_proto_rawDescOnce.Do(func() {
		file_proto_fastls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fastls_proto_rawDesc), len(file_proto_fastls_proto_rawDesc)))
	})
	return file_proto_fastls_proto_rawDescData
}

var file_proto_fastls_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_fastls_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: fastls.HealthRequest
	(*HealthResponse)(nil), // 1: fastls.HealthResponse
	(*FetchRequest)(nil),   // 2: fastls.FetchRequest
	(*Fingerprint)(nil),    // 3: fastls.Fingerprint
	(*Cookie)(nil),         // 4: fastls.Cookie
	(*FetchResponse)(nil),  // 5: fastls.FetchResponse
	nil,                    // 6: fastls.FetchRequest.HeadersEntry
	nil,                    // 7: fastls.FetchResponse.HeadersEntry
}
var file_proto_fastls_proto_depIdxs = []int32{
	6, // 0: fastls.FetchRequest.headers:type_name -> fastls.FetchRequest.HeadersEntry
	3, // 1: fastls.FetchRequest.fingerprint:type_name -> fastls.Fingerprint
	4, // 2: fastls.FetchRequest.cookies:type_name -> fastls.Cookie
	7, // 3: fastls.FetchResponse.headers:type_name -> fastls.FetchResponse.HeadersEntry
	0, // 4: fastls.FastlsService.Health:input_type -> fastls.HealthRequest
	2, // 5: fastls.FastlsService.Fetch:input_type -> fastls.FetchRequest
	1, // 6: fastls.FastlsService.Health:output_type -> fastls.HealthResponse
	5, // 7: fastls.FastlsService.Fetch:output_type -> fastls.FetchResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_fastls_proto_init() }
func file_proto_fastls_proto_init() {
	if File_proto_fastls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fastls_proto_rawDesc), len(file_proto_fastls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fastls_proto_goTypes,
		DependencyIndexes: file_proto_fastls_proto_depIdxs,
		MessageInfos:      file_proto_fastls_proto_msgTypes,
	}.Build()
	File_proto_fastls_proto = out.File
	file_proto_fastls_proto_goTypes = nil
	file_proto_fastls_proto_depIdxs = nil
}
